language: bash
env:
  global:
    - GIT_COMMITTER_NAME=rcmdnk
    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
    - GIT_AUTHOR_NAME=rcmdnk
    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
    - secure: "OHol8QUh2GtqoMk4VLExaVg2iRdkvP7typryQaY4Mh/Kk2k4kcz326uD6BoUkidgjcAb0cdK4Yvf04Tas2Q9sdCSSh6Qp8JUaZyB4XwBZiJ9yadAMUl7Sui3t8wEJ4ZVWL6SX6a+XVNCasvZsJGuKTkXdt6NpDWAV1f/6UEM5bU="
before_install:
  #- openssl aes-256-cbc -K $encrypted_a28e27acd1e7_key -iv $encrypted_a28e27acd1e7_iv -in id_rsa.enc -out id_rsa -d
  - openssl aes-256-cbc -K $encrypted_a28e27acd1e7_key -iv $encrypted_a28e27acd1e7_iv -in id_rsa_test.enc -out id_rsa_test -d
script:
  - echo test
  - git config --global push.default simple
  - git branch
  - git checkout -b test
  - git branch
  - touch testfile
  - echo "test" >> testfile
  - rm -f .travis.yml
  - git add -A
  - git commit -m "test commit"
  - git push --quiet -f https://${GH_TOKEN}@github.com/rcmdnk/travis-test test
  - echo "test2" >> testfile
  - echo "test" >> testfile2
  - git add -A
  - git commit -m "test commit2"
  - ls ~/.ssh/
  - cp id_rsa ~/.ssh/
  - chmod 600 ~/.ssh/id_rsa
  - git push -f git@github.com:rcmdnk/travis-test test
  - cp id_rsa_test ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo "test2" >> testfile
  - echo "test" >> testfile2
  - git add -A
  - git commit -m "test commit2"
  - git push -f git@github.com:rcmdnk/octogray_test test
  - echo "test2" >> testfile
  - echo "test" >> testfile2
  - git add -A
  - git commit -m "test commit2"
  - git push -f git@github.com:rcmdnk/travis-test test
