language: objective-c
script:
  - echo test
  - echo $SHELL
  - bash --version
  - which csh
  - echo test >& log
  - brew install csh
  - echo test >& log
  - which sh
  - ls -l /bin/sh
  - sh -c "echo test >& log"
